indir: no  # to be overriden in CLI
outdir: no  # to be overriden in CLI

model:
  paths: [/ocean/projects/cis220039p/cherieho/map-explore/lama/experiments/cherieho_notrain, /ocean/projects/cis220039p/cherieho/map-explore/lama/experiments/cherieho_2024-02-12_14-25-41_train_big-lama_]  
  display_names: [Original, Finetuned]
  checkpoint: best.ckpt

dataset:
  kind: actual_mask
  pad_out_to_modulo: 8
  transform_variant: default_map_eval
  num_frames_to_skip: 10

device: cuda
out_key: inpainted

refine: False # refiner will only run if this is True
refiner:
  gpu_ids: 0, # the GPU ids of the machine to use. If only single GPU, use: "0,"
  modulo: ${dataset.pad_out_to_modulo}
  n_iters: 15 # number of iterations of refinement for each scale
  lr: 0.002 # learning rate
  min_side: 512 # all sides of image on all scales should be >= min_side / sqrt(2)
  max_scales: 3 # max number of downscaling scales for the image-mask pyramid
  px_budget: 1800000 # pixels budget. Any image will be resized to satisfy height*width <= px_budget