data_root_dir: /ocean/projects/cis220039p/cherieho/map-explore/map_prediction_toolbox_outputs/training_inputs/1124_datacollect_v2_jobs_global_split_to_3/
train_subdir: train_2
out_root_dir: /ocean/projects/cis220039p/cherieho/map-explore/lama/experiments/
tb_dir: /ocean/projects/cis220039p/cherieho/map-explore/lama/tb_logs/
